spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${URL_DATABASE:jdbc:postgresql://localhost:5433/hackathon_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:12345}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    open-in-view: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect