-- MASS OF DATA
-- USERS
INSERT INTO users_tb(name, email, password, exchange) VALUES('Test-1', 'test-1@test.com', '11111111', 'Mail')
INSERT INTO users_tb(name, email, password, exchange) VALUES('Test-2', 'test-2@test.com', '22222222', 'In person')
INSERT INTO users_tb(name, email, password, exchange) VALUES('Test-3', 'test-3@test.com', '33333333', 'Mail')
INSERT INTO users_tb(name, email, password, exchange) VALUES('Test-4', 'test-4@test.com', '44444444', 'In person')
INSERT INTO users_tb(name, email, password, exchange) VALUES('Test-5', 'test-5@test.com', '55555555', 'Mail')
INSERT INTO users_tb(name, email, password, exchange) VALUES('Test-6', 'test-6@test.com', '66666666', 'In person')
INSERT INTO users_tb(name, email, password, exchange) VALUES('Test-7', 'test-7@test.com', '77777777', 'Mail')
INSERT INTO users_tb(name, email, password, exchange) VALUES('Test-8', 'test-8@test.com', '88888888', 'In person')
INSERT INTO users_tb(name, email, password, exchange) VALUES('Test-9', 'test-9@test.com', '99999999', 'Mail')
INSERT INTO users_tb(name, email, password, exchange) VALUES('Test-10', 'test-10@test.com', '99999999', 'In person')
INSERT INTO users_tb(name, email, password, exchange) VALUES('Test-11', 'test-11@test.com', '99999999', 'Mail')
INSERT INTO users_tb(name, email, password, exchange) VALUES('Test-12', 'test-12@test.com', '99999999', 'In person')
INSERT INTO users_tb(name, email, password, exchange) VALUES('Test-13', 'test-13@test.com', '99999999', 'Mail')
INSERT INTO users_tb(name, email, password, exchange) VALUES('Test-14', 'test-14@test.com', '99999999', 'In person')
INSERT INTO users_tb(name, email, password, exchange) VALUES('Test-15', 'test-15@test.com', '99999999', 'Mail')
INSERT INTO users_tb(name, email, password, exchange) VALUES('Test-16', 'test-16@test.com', '99999999', 'In person')
INSERT INTO users_tb(name, email, password, exchange) VALUES('Test-17', 'test-17@test.com', '99999999', 'Mail')
INSERT INTO users_tb(name, email, password, exchange) VALUES('Test-18', 'test-18@test.com', '99999999', 'In person')
INSERT INTO users_tb(name, email, password, exchange) VALUES('Test-19', 'test-19@test.com', '99999999', 'Mail')
INSERT INTO users_tb(name, email, password, exchange) VALUES('Test-20', 'test-20@test.com', '99999999', 'In person')

-- GAMES
INSERT INTO games_tb(name, brand, user_id) VALUES('Splatoon', 'Nintendo', 2)
INSERT INTO games_tb(name, brand, user_id) VALUES('Mario Kart Deluxe 8', 'Nintendo', 1)
INSERT INTO games_tb(name, brand, user_id) VALUES('Zelda - BOTW', 'Nintendo', 1)
INSERT INTO games_tb(name, brand, user_id) VALUES('Zelda - TOTK', 'Nintendo', 2)
INSERT INTO games_tb(name, brand, user_id) VALUES('Resident Evil 4', 'PS4', 3)
INSERT INTO games_tb(name, brand, user_id) VALUES('Fifa 24', 'PS5', 3)
INSERT INTO games_tb(name, brand, user_id) VALUES('Forza Horizon 5', 'X-Box One', 4)
INSERT INTO games_tb(name, brand, user_id) VALUES('GTA - San Adreas', 'PS2', 5)
INSERT INTO games_tb(name, brand, user_id) VALUES('GTA V', 'PS4', 6)
INSERT INTO games_tb(name, brand, user_id) VALUES('The Last of US I', 'PS4', 6)
INSERT INTO games_tb(name, brand, user_id) VALUES('The Last of US II', 'PS5', 9)
INSERT INTO games_tb(name, brand, user_id) VALUES('The Last of US I', 'PS5', 9)
INSERT INTO games_tb(name, brand, user_id) VALUES('Splatoon', 'Nintendo', 7)
INSERT INTO games_tb(name, brand, user_id) VALUES('Mario Marker', 'Nintendo', 8)
INSERT INTO games_tb(name, brand, user_id) VALUES('Elden Ring', 'X-Box One', 8)
INSERT INTO games_tb(name, brand, user_id) VALUES('Destiny 2', 'X-Box One', 7)
