version: '3'

services:
  sonarqube:
    image: sonarqube:lts-community
    ports:
      - "9000:9000"
    env_file:
      - variables-sonarqube.env
    networks:
      - sonar-network
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  sonar_db:
    image: postgres:latest
    env_file:
      - variables-sonarqube-db.env
    ports:
      - "5434:5432"
    networks:
      - sonar-network
    volumes:
      - postgres:/var/lib/postgresql

  sonar_scanner:
    image: finalgene/sonar-scanner
    environment:
      SONAR_HOST_URL: http://localhost:9000
      SONAR_LOGIN_TOKEN: squ_b18595f91cc1c0850336a3334cdeecc334dde816
    networks:
      - sonar-network
    volumes:
      - sonar_scan:/cache/.sonar
    depends_on:
      - sonarqube

networks:
  sonar-network:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonar_scan:
  postgres: